import 'dart:convert';
import 'package:logger/logger.dart';
import 'package:edtech_offline_app/src/core/database/database_helper.dart';
import 'package:edtech_offline_app/src/features/ai_assistant/data/ai_repository.dart';
import 'package:edtech_offline_app/src/features/quiz_exam_gen/data/models/exam_model.dart';

class PaperGenerationService {
  final AIRepository _aiRepository;
  final DatabaseHelper _dbHelper = DatabaseHelper.instance;
  final Logger _logger = Logger();

  PaperGenerationService(this._aiRepository);

  // FIXED: Auto-generate Basic or Advanced tier paper (100 marks)
  Future<ExamModel?> generateExamPaper({
    required String title,
    required String difficulty, // "Basic" or "Advanced"
    required List<String> topics,
    required String rawContent, // Chapter text for AI
    void Function(double progress)? onProgress,
  }) async {
    try {
      // Fixed timer and marks for requirements compliance
      final int timerMinutes = 120; // 2 hours for exam
      final int totalMarks = 100; // Fixed 100 marks

      // Get question structure based on tier
      final types = _getTierStructure(difficulty);

      final db = await _dbHelper.database;
      List<QuestionModel> questionModels = [];

      // Generate each section
      int processedSections = 0;
      for (var typeConfig in types) {
        final questions = await _generateSection(
          rawContent: rawContent,
          difficulty: difficulty,
          type: typeConfig['type'],
          count: typeConfig['count'],
          marks: typeConfig['marks'],
          topics: topics,
        );

        questionModels.addAll(questions);
        processedSections++;
        onProgress?.call(processedSections / types.length);
      }

      if (questionModels.isEmpty) {
        _logger.w("⚠️ No questions generated by AI for exam");
        return null;
      }

      final exam = ExamModel(
        title: title,
        difficulty: difficulty,
        timestamp: DateTime.now().toIso8601String(),
        timerMinutes: timerMinutes,
        totalMarks: totalMarks,
        type: "exam",
        questions: questionModels,
      );

      // Save exam directly to DB
      final examId = await db.insert('exams', exam.toMap());
      exam.id = examId;
      for (var q in exam.questions) {
        await db.insert('questions', q.toMap()..['exam_id'] = examId);
      }

      _logger.i("✅ Exam '${exam.title}' generated and saved with ID $examId");
      return exam;
    } catch (e) {
      _logger.e("❌ Exam generation failed: $e");
      return null;
    }
  }

  // FIXED: Get tier-specific question structure (100 marks)
  List<Map<String, dynamic>> _getTierStructure(String difficulty) {
    if (difficulty == "Basic") {
      // Basic Tier: Section A (20) + B (15) + C (35) + D (30) = 100
      return [
        {'type': 'MCQ', 'count': 5, 'marks': 1},
        {'type': 'Fill-up', 'count': 5, 'marks': 1},
        {'type': 'OddOneOut', 'count': 5, 'marks': 1},
        {'type': 'Rearrange', 'count': 5, 'marks': 1},
        {'type': 'MatchIt', 'count': 5, 'marks': 3},
        {'type': 'ShortAns', 'count': 7, 'marks': 5},
        {'type': 'LongAns', 'count': 3, 'marks': 10},
      ];
    } else {
      // Advanced Tier: Section A (20) + B (25) + C (5) + D (50) = 100
      return [
        {'type': 'MCQ', 'count': 5, 'marks': 1},
        {'type': 'Fill-up', 'count': 5, 'marks': 1},
        {'type': 'True/False', 'count': 5, 'marks': 1},
        {'type': 'OddOneOut', 'count': 5, 'marks': 1},
        {'type': 'ShortAns', 'count': 5, 'marks': 5},
        {'type': 'CaseStudy', 'count': 1, 'marks': 5},
        {'type': 'LongAns', 'count': 5, 'marks': 10},
      ];
    }
  }

  // Generate questions for a specific section
  Future<List<QuestionModel>> _generateSection({
    required String rawContent,
    required String difficulty,
    required String type,
    required int count,
    required int marks,
    required List<String> topics,
  }) async {
    try {
      final prompt = _buildSectionPrompt(
        rawContent,
        difficulty,
        type,
        count,
        marks,
        topics,
      );

      final questions = await _aiRepository.generateAssessment(prompt: prompt);

      if (questions.isEmpty) {
        _logger.w("⚠️ No questions generated for $type");
        return [];
      }

      final db = await _dbHelper.database;
      List<QuestionModel> questionModels = [];

      for (var q in questions) {
        final text = q['question'] ?? '';
        if (text.isEmpty) continue;

        final hash = text.hashCode.toString();
        final existing = await db.query(
          'question_history',
          where: 'question_hash = ?',
          whereArgs: [hash],
        );

        if (existing.isEmpty) {
          await db.insert('question_history', {
            'chapter_title': q['chapter_title'] ?? '',
            'topic': q['topic'] ?? '',
            'question_hash': hash,
            'generated_at': DateTime.now().toIso8601String(),
          });

          questionModels.add(QuestionModel.fromMap({
            'type': type,
            'question_text': text,
            'options': jsonEncode(q['options'] ?? []),
            'correct_answer': q['correct'] ?? q['answer'] ?? '',
            'explanation': q['explanation'] ?? '',
            'marks': marks,
            'image_path': q['image_path'],
          }));
        }
      }

      return questionModels;
    } catch (e) {
      _logger.e("❌ Section generation error: $e");
      return [];
    }
  }

  String _buildSectionPrompt(
    String rawContent,
    String difficulty,
    String type,
    int count,
    int marks,
    List<String> topics,
  ) {
    final topicList = topics.join(", ");
    String instructions = "";

    switch (type) {
      case 'MCQ':
        instructions = "Generate $count Multiple Choice Questions with 4 options each.";
        break;
      case 'Fill-up':
        instructions = "Generate $count Fill-in-the-blank questions with hints.";
        break;
      case 'True/False':
        instructions = "Generate $count True/False statements.";
        break;
      case 'OddOneOut':
        instructions = "Generate $count 'Odd One Out' questions with 4 items.";
        break;
      case 'Rearrange':
        instructions = "Generate $count sentence rearrangement questions.";
        break;
      case 'MatchIt':
        instructions = "Generate $count matching pairs (left item = question, right match = answer).";
        break;
      case 'CaseStudy':
        instructions = "Generate 1 case study with scenario and analytical question.";
        break;
      case 'ShortAns':
        instructions = "Generate $count short answer questions (2-3 sentences).";
        break;
      case 'LongAns':
        instructions = "Generate $count detailed answer questions (5-6 sentences).";
        break;
      default:
        instructions = "Generate $count questions.";
    }

    return """
$instructions
Difficulty: $difficulty
Topics: $topicList
Marks per question: $marks

Content:
$rawContent

Output JSON array with fields:
- question
- options (array, empty for fill-up/short/long)
- correct (or answer)
- explanation
""";
  }
}