import 'dart:convert';
import 'package:logger/logger.dart';
import 'package:edtech_offline_app/src/core/database/database_helper.dart';
import 'package:edtech_offline_app/src/features/ai_assistant/data/ai_repository.dart';
import 'package:edtech_offline_app/src/features/quiz_exam_gen/data/models/exam_model.dart';

class QuizGenerationService {
  final AIRepository _aiRepository;
  final DatabaseHelper _dbHelper = DatabaseHelper.instance;
  final Logger _logger = Logger();

  QuizGenerationService(this._aiRepository);

  Future<ExamModel?> generateQuiz({
    required String title,
    required String difficulty,
    required List<String> topics,
    required int timerMinutes, // ✅ teacher-provided
    required int totalMarks, // ✅ teacher-provided
    required List<Map<String, dynamic>> types,
    void Function(double progress)? onProgress,
  }) async {
    try {
      final prompt = _buildPrompt(
        title,
        difficulty,
        topics,
        timerMinutes,
        totalMarks,
        types,
      );

      final responseText = await _aiRepository.generateText(prompt);

      // Parse the AI response to extract questions
      List<Map<String, dynamic>> questions = [];
      try {
        final parsed = jsonDecode(responseText);
        if (parsed is List) {
          questions = parsed.cast<Map<String, dynamic>>();
        } else if (parsed is Map && parsed.containsKey('questions')) {
          questions =
              (parsed['questions'] as List).cast<Map<String, dynamic>>();
        }
      } catch (e) {
        _logger.e("Failed to parse AI response: $e");
      }

      if (questions.isEmpty) {
        _logger.w("⚠️ No questions generated by AI for quiz");
        return null;
      }

      final db = await _dbHelper.database;
      List<QuestionModel> questionModels = [];

      for (int i = 0; i < questions.length; i++) {
        final q = questions[i];
        final text = q['question'] ?? '';
        final hash = text.hashCode.toString();

        final existing = await db.query(
          'question_history',
          where: 'question_hash = ?',
          whereArgs: [hash],
        );

        if (existing.isEmpty) {
          await db.insert('question_history', {
            'chapter_title': q['chapter_title'] ?? '',
            'topic': q['topic'] ?? '',
            'question_hash': hash,
            'generated_at': DateTime.now().toIso8601String(),
          });

          questionModels.add(QuestionModel.fromMap({
            'type': q['type'] ?? 'MCQ',
            'question_text': text,
            'options': jsonEncode(q['options'] ?? []),
            'correct_answer': q['correct'] ?? '',
            'explanation': q['explanation'] ?? '',
            'marks': q['marks'] ?? 1,
            'image_path': q['image_path'],
          }));
        }

        onProgress?.call((i + 1) / questions.length);
      }

      final quiz = ExamModel(
        title: title,
        difficulty: difficulty,
        timestamp: DateTime.now().toIso8601String(),
        timerMinutes: timerMinutes,
        totalMarks: totalMarks,
        type: "quiz", // ✅ enforce quiz type
        questions: questionModels,
      );

      // Save quiz directly to DB
      final quizId = await db.insert('exams', quiz.toMap());

      for (var q in quiz.questions) {
        await db.insert('questions', q.toMap()..['exam_id'] = quizId);
      }

      _logger.i("✅ Quiz '${quiz.title}' generated and saved with ID $quizId");
      return quiz;
    } catch (e) {
      _logger.e("❌ Quiz generation failed: $e");
      return null;
    }
  }

  String _buildPrompt(
    String title,
    String difficulty,
    List<String> topics,
    int timerMinutes,
    int totalMarks,
    List<Map<String, dynamic>> types,
  ) {
    final topicList = topics.join(", ");
    final typeDetails = types
        .map((t) => "${t['count']} x ${t['type']} (marks: ${t['marks']} each)")
        .join(", ");

    return """
Generate a $difficulty quiz titled "$title".
Include questions from these topics: $topicList.
Quiz duration: $timerMinutes minutes.
Total marks: $totalMarks.
Question types requested: $typeDetails.
Format output as JSON list with fields:
- question
- options
- correct
- explanation
- marks
- type
- image_path
""";
  }
}
