name: Flutter Android Build

on:
  push:
    branches:
      - login   # runs only when you push to login branch
  workflow_dispatch: # allows manual trigger from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.5' # match your Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk